/**
 * Generated by Agitar build: Agitator Version 1.0.4.000276 (Build date: Mar 27, 2007) [1.0.4.000276]
 * JDK Version: 1.5.0_09
 *
 * Generated on 04-Apr-2007 08:29:41
 * Time to generate: 00:07.603 seconds
 *
 */

package agitar.uk.ac.ebi.intact.modelt;
import uk.ac.ebi.intact.model.*;

import com.agitar.lib.junit.AgitarTestCase;
import uk.ac.ebi.intact.model.util.AnnotatedObjectUtils;

public class CvDatabaseAgitarTest extends AgitarTestCase {

    static Class TARGET_CLASS = CvDatabase.class;

    public void testConstructor() throws Throwable {
        Institution owner = new Institution( "testCvDatabaseShortLabel" );
        CvDatabase cvDatabase = new CvDatabase( owner, "testCvDatabaseShortLabel" );
        assertEquals( "cvDatabase.xrefs.size()", 0, cvDatabase.xrefs.size() );
        assertEquals( "cvDatabase.getAliases().size()", 0, cvDatabase.getAliases().size() );
        assertEquals( "cvDatabase.getEvidences().size()", 0, cvDatabase.getEvidences().size() );
        assertEquals( "cvDatabase.shortLabel", "testCvDatabaseShortL", cvDatabase.getShortLabel() );
        assertEquals( "cvDatabase.annotations.size()", 0, cvDatabase.annotations.size() );
        assertSame( "cvDatabase.getOwner()", owner, cvDatabase.getOwner() );
        assertEquals( "cvDatabase.references.size()", 0, cvDatabase.references.size() );
    }

    public void testConstructorThrowsIllegalArgumentException() throws Throwable {
        try {
            new CvDatabase( new Institution( "testCvDatabaseShortLabel" ), "" );
            fail( "Expected IllegalArgumentException to be thrown" );
        } catch ( IllegalArgumentException ex ) {
            assertEquals( "ex.getMessage()", "Must define a non empty short label", ex.getMessage() );
            assertThrownBy( AnnotatedObjectUtils.class, ex );
        }
    }

    public void testConstructorThrowsNullPointerException() throws Throwable {
        try {
            new CvDatabase( new Institution( "testCvDatabaseShortLabel" ), null );
            fail( "Expected NullPointerException to be thrown" );
        } catch ( NullPointerException ex ) {
            assertEquals( "ex.getMessage()", "Must define a non null short label", ex.getMessage() );
            assertThrownBy( AnnotatedObjectUtils.class, ex );
        }
    }
}

