/**
 * Generated by Agitar build: Agitator Version 1.0.4.000276 (Build date: Mar 27, 2007) [1.0.4.000276]
 * JDK Version: 1.5.0_09
 *
 * Generated on 04-Apr-2007 08:22:35
 * Time to generate: 00:07.756 seconds
 *
 */

package agitar.uk.ac.ebi.intact.modelt; import uk.ac.ebi.intact.model.*;

import com.agitar.lib.junit.AgitarTestCase;
import uk.ac.ebi.intact.model.util.AnnotatedObjectUtils;

public class CvTopicAgitarTest extends AgitarTestCase {

    static Class TARGET_CLASS = CvTopic.class;

    public void testConstructor() throws Throwable {
        Institution owner = new Institution( "testCvTopicShortLabel" );
        CvTopic cvTopic = new CvTopic( owner, "testCvTopicShortLabel" );
        assertEquals( "cvTopic.xrefs.size()", 0, cvTopic.xrefs.size() );
        assertEquals( "cvTopic.getAliases().size()", 0, cvTopic.getAliases().size() );
        assertEquals( "cvTopic.getEvidences().size()", 0, cvTopic.getEvidences().size() );
        assertEquals( "cvTopic.shortLabel", "testCvTopicShortLabe", cvTopic.getShortLabel() );
        assertEquals( "cvTopic.annotations.size()", 0, cvTopic.annotations.size() );
        assertSame( "cvTopic.getOwner()", owner, cvTopic.getOwner() );
        assertEquals( "cvTopic.references.size()", 0, cvTopic.references.size() );
    }

    public void testConstructorThrowsIllegalArgumentException() throws Throwable {
        try {
            new CvTopic( new Institution( "testCvTopicShortLabel" ), "" );
            fail( "Expected IllegalArgumentException to be thrown" );
        } catch ( IllegalArgumentException ex ) {
            assertEquals( "ex.getMessage()", "Must define a non empty short label", ex.getMessage() );
            assertThrownBy( AnnotatedObjectUtils.class, ex );
        }
    }

    public void testConstructorThrowsNullPointerException() throws Throwable {
        try {
            new CvTopic( new Institution( "testCvTopicShortLabel" ), null );
            fail( "Expected NullPointerException to be thrown" );
        } catch ( NullPointerException ex ) {
            assertEquals( "ex.getMessage()", "Must define a non null short label", ex.getMessage() );
            assertThrownBy( AnnotatedObjectUtils.class, ex );
        }
    }
}

