/**
 * Generated by Agitar build: Agitator Version 1.0.4.000276 (Build date: Mar 27, 2007) [1.0.4.000276]
 * JDK Version: 1.5.0_09
 *
 * Generated on 04-Apr-2007 08:24:03
 * Time to generate: 00:52.306 seconds
 *
 */

package agitar.uk.ac.ebi.intact.modelt; import uk.ac.ebi.intact.model.*;

import com.agitar.lib.junit.AgitarTestCase;
import com.agitar.lib.mockingbird.Mockingbird;

import java.util.ArrayList;

public class MineInteractionAgitarTest extends AgitarTestCase {

    static Class TARGET_CLASS = MineInteraction.class;

    public void testConstructor() throws Throwable {
        MineInteraction mineInteraction = new MineInteraction();
        assertNull( "mineInteraction.getInteractionAc()", mineInteraction.getInteractionAc() );
    }

    public void testConstructor1() throws Throwable {
        ProteinImpl protein1 = new ProteinImpl( new Institution( "testMineInteractionShortLabel1" ), new BioSource( new Institution( "testMineInteractionShortLabel" ), "testMineInteractionShortLabel", "-68833" ), "testMineInteractionShortLabel" );
        InteractionImpl interaction = new InteractionImpl( new ArrayList( 100 ), new ArrayList( 1000 ), ( CvInteractionType ) null, "testMineInteractionShortLabel", new Institution( "testMineInteractionShortLabel2" ) );
        MineInteraction mineInteraction = new MineInteraction( protein1, protein1, interaction );
        assertSame( "mineInteraction.getPk().getInteraction()", interaction, mineInteraction.getPk().getInteraction() );
        assertEquals( "mineInteraction.getShortLabel1()", "testMineInteractionS", mineInteraction.getShortLabel1() );
        assertEquals( "mineInteraction.getShortLabel2()", "testMineInteractionS", mineInteraction.getShortLabel2() );
    }

    public void testEquals() throws Throwable {
        MineInteraction o = new MineInteraction();
        o.setWeight( -1.0 );
        boolean result = new MineInteraction().equals( o );
        assertFalse( "result", result );
    }

    public void testEquals1() throws Throwable {
        MineInteractionPk pk = new MineInteractionPk();
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setPk( pk );
        MineInteraction o = new MineInteraction();
        o.setPk( pk );
        boolean result = mineInteraction.equals( o );
        assertTrue( "result", result );
        assertSame( "mineInteraction.getPk()", pk, mineInteraction.getPk() );
    }

    public void testEquals2() throws Throwable {
        CvTopic detectionMethod = new CvTopic( new Institution( "testMineInteractionShortLabel" ), "testMineInteractionShortLabel" );
        MineInteractionPk pk = new MineInteractionPk();
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setDetectionMethod( detectionMethod );
        mineInteraction.setGraphId( 48 );
        mineInteraction.setPk( pk );
        MineInteraction o = new MineInteraction();
        o.setGraphId( 48 );
        o.setPk( pk );
        boolean result = mineInteraction.equals( o );
        assertFalse( "result", result );
        assertSame( "mineInteraction.getPk()", pk, mineInteraction.getPk() );
        assertSame( "mineInteraction.getDetectionMethod()", detectionMethod, mineInteraction.getDetectionMethod() );
    }

    public void testEquals3() throws Throwable {
        boolean result = new MineInteraction().equals( new MineInteraction() );
        assertTrue( "result", result );
    }

    public void testEquals4() throws Throwable {
        MineInteraction o = new MineInteraction();
        o.setPubmedId( "testMineInteractionPubmedId" );
        boolean result = new MineInteraction().equals( o );
        assertFalse( "result", result );
    }

    public void testEquals5() throws Throwable {
        MineInteractionPk pk = new MineInteractionPk();
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setWeight( -1.0 );
        mineInteraction.setGraphId( 48 );
        mineInteraction.setPk( pk );
        MineInteraction o = new MineInteraction();
        o.setGraphId( 48 );
        o.setPk( pk );
        boolean result = mineInteraction.equals( o );
        assertFalse( "result", result );
        assertSame( "mineInteraction.getPk()", pk, mineInteraction.getPk() );
    }

    public void testEquals6() throws Throwable {
        MineInteraction o = new MineInteraction();
        o.setShortLabel2( "testMineInteractionShortLabel2" );
        boolean result = new MineInteraction().equals( o );
        assertFalse( "result", result );
    }

    public void testEquals7() throws Throwable {
        boolean result = new MineInteraction().equals( "" );
        assertFalse( "result", result );
    }

    public void testEquals8() throws Throwable {
        MineInteractionPk pk = new MineInteractionPk();
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setPk( pk );
        boolean result = mineInteraction.equals( new MineInteraction() );
        assertFalse( "result", result );
        assertSame( "mineInteraction.getPk()", pk, mineInteraction.getPk() );
    }

    public void testEquals9() throws Throwable {
        MineInteraction o = new MineInteraction();
        boolean result = o.equals( o );
        assertTrue( "result", result );
    }

    public void testEquals10() throws Throwable {
        boolean result = new MineInteraction().equals( null );
        assertFalse( "result", result );
    }

    public void testEquals11() throws Throwable {
        MineInteraction o = new MineInteraction();
        o.setGraphId( 100 );
        boolean result = new MineInteraction().equals( o );
        assertFalse( "result", result );
    }

    public void testEquals12() throws Throwable {
        MineInteractionPk pk = new MineInteractionPk();
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setGraphId( 100 );
        mineInteraction.setPk( pk );
        MineInteraction o = new MineInteraction();
        o.setPk( pk );
        boolean result = mineInteraction.equals( o );
        assertFalse( "result", result );
        assertSame( "mineInteraction.getPk()", pk, mineInteraction.getPk() );
    }

    public void testHashCode() throws Throwable {
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setShortLabel1( "testMineInteractionShortLabel1" );
        mineInteraction.setTaxid( "testMineInteractionTaxid" );
        int result = mineInteraction.hashCode();
        assertEquals( "result", 147249307, result );
        assertNull( "mineInteraction.getPk()", mineInteraction.getPk() );
        assertEquals( "mineInteraction.getTaxid()", "testMineInteractionTaxid", mineInteraction.getTaxid() );
        assertNull( "mineInteraction.getExperiment()", mineInteraction.getExperiment() );
        assertNull( "mineInteraction.getPubmedId()", mineInteraction.getPubmedId() );
        assertEquals( "mineInteraction.getShortLabel1()", "testMineInteractionShortLabel1", mineInteraction.getShortLabel1() );
        assertNull( "mineInteraction.getShortLabel2()", mineInteraction.getShortLabel2() );
        assertNull( "mineInteraction.getDetectionMethod()", mineInteraction.getDetectionMethod() );
    }

    public void testHashCode1() throws Throwable {
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setShortLabel2( "testMineInteractionShortLabel2" );
        mineInteraction.setShortLabel1( "testMineInteractionShortLabel1" );
        int result = mineInteraction.hashCode();
        assertEquals( "result", -461462335, result );
        assertNull( "mineInteraction.getPk()", mineInteraction.getPk() );
        assertNull( "mineInteraction.getTaxid()", mineInteraction.getTaxid() );
        assertNull( "mineInteraction.getExperiment()", mineInteraction.getExperiment() );
        assertNull( "mineInteraction.getPubmedId()", mineInteraction.getPubmedId() );
        assertEquals( "mineInteraction.getShortLabel1()", "testMineInteractionShortLabel1", mineInteraction.getShortLabel1() );
        assertEquals( "mineInteraction.getShortLabel2()", "testMineInteractionShortLabel2", mineInteraction.getShortLabel2() );
        assertNull( "mineInteraction.getDetectionMethod()", mineInteraction.getDetectionMethod() );
    }

    public void testHashCode2() throws Throwable {
        MineInteractionPk pk = new MineInteractionPk();
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setTaxid( "testMineInteractionTaxid" );
        mineInteraction.setPk( pk );
        int result = mineInteraction.hashCode();
        assertEquals( "result", 1185624679, result );
        assertSame( "mineInteraction.getPk()", pk, mineInteraction.getPk() );
        assertEquals( "mineInteraction.getTaxid()", "testMineInteractionTaxid", mineInteraction.getTaxid() );
        assertNull( "mineInteraction.getExperiment()", mineInteraction.getExperiment() );
        assertNull( "mineInteraction.getPubmedId()", mineInteraction.getPubmedId() );
        assertNull( "mineInteraction.getShortLabel1()", mineInteraction.getShortLabel1() );
        assertNull( "mineInteraction.getShortLabel2()", mineInteraction.getShortLabel2() );
        assertNull( "mineInteraction.getDetectionMethod()", mineInteraction.getDetectionMethod() );
    }

    public void testHashCode3() throws Throwable {
        MineInteractionPk pk = new MineInteractionPk();
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setPk( pk );
        int result = mineInteraction.hashCode();
        assertEquals( "result", 0, result );
        assertSame( "mineInteraction.getPk()", pk, mineInteraction.getPk() );
        assertNull( "mineInteraction.getTaxid()", mineInteraction.getTaxid() );
        assertNull( "mineInteraction.getExperiment()", mineInteraction.getExperiment() );
        assertNull( "mineInteraction.getPubmedId()", mineInteraction.getPubmedId() );
        assertNull( "mineInteraction.getShortLabel1()", mineInteraction.getShortLabel1() );
        assertNull( "mineInteraction.getShortLabel2()", mineInteraction.getShortLabel2() );
        assertNull( "mineInteraction.getDetectionMethod()", mineInteraction.getDetectionMethod() );
    }

    public void testHashCode4() throws Throwable {
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setShortLabel1( "testMineInteractionShortLabel1" );
        int result = mineInteraction.hashCode();
        assertEquals( "result", -1038375372, result );
        assertNull( "mineInteraction.getPk()", mineInteraction.getPk() );
        assertNull( "mineInteraction.getTaxid()", mineInteraction.getTaxid() );
        assertNull( "mineInteraction.getExperiment()", mineInteraction.getExperiment() );
        assertNull( "mineInteraction.getPubmedId()", mineInteraction.getPubmedId() );
        assertEquals( "mineInteraction.getShortLabel1()", "testMineInteractionShortLabel1", mineInteraction.getShortLabel1() );
        assertNull( "mineInteraction.getShortLabel2()", mineInteraction.getShortLabel2() );
        assertNull( "mineInteraction.getDetectionMethod()", mineInteraction.getDetectionMethod() );
    }

    public void testHashCode5() throws Throwable {
        MineInteractionPk pk = new MineInteractionPk();
        CvTopic detectionMethod = new CvTopic( new Institution( "testMineInteractionShortLabel" ), "testMineInteractionShortLabel" );
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setShortLabel2( "testMineInteractionShortLabel2" );
        mineInteraction.setDetectionMethod( detectionMethod );
        mineInteraction.setShortLabel1( "testMineInteractionShortLabel1" );
        mineInteraction.setPk( pk );
        int result = mineInteraction.hashCode();
        assertEquals( "result", -1117179352, result );
        assertSame( "mineInteraction.getPk()", pk, mineInteraction.getPk() );
        assertNull( "mineInteraction.getTaxid()", mineInteraction.getTaxid() );
        assertNull( "mineInteraction.getExperiment()", mineInteraction.getExperiment() );
        assertNull( "mineInteraction.getPubmedId()", mineInteraction.getPubmedId() );
        assertEquals( "mineInteraction.getShortLabel1()", "testMineInteractionShortLabel1", mineInteraction.getShortLabel1() );
        assertEquals( "mineInteraction.getShortLabel2()", "testMineInteractionShortLabel2", mineInteraction.getShortLabel2() );
        assertSame( "mineInteraction.getDetectionMethod()", detectionMethod, mineInteraction.getDetectionMethod() );
    }

    public void testHashCode6() throws Throwable {
        Experiment experiment = new Experiment( new Institution( "testMineInteractionShortLabel1" ), "testMineInteractionShortLabel", new BioSource( new Institution( "testMineInteractionShortLabel" ), "testMineInteractionShortLabel", "-68833" ) );
        CvTopic detectionMethod = new CvTopic( new Institution( "testMineInteractionShortLabel2" ), "testMineInteractionShortLabel" );
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setPubmedId( "testMineInteractionPubmedId" );
        mineInteraction.setShortLabel2( "testMineInteractionShortLabel2" );
        mineInteraction.setDetectionMethod( detectionMethod );
        mineInteraction.setExperiment( experiment );
        mineInteraction.setShortLabel1( "testMineInteractionShortLabel1" );
        mineInteraction.setTaxid( "testMineInteractionTaxid" );
        int result = mineInteraction.hashCode();
        assertEquals( "result", 405133527, result );
        assertNull( "mineInteraction.getPk()", mineInteraction.getPk() );
        assertEquals( "mineInteraction.getTaxid()", "testMineInteractionTaxid", mineInteraction.getTaxid() );
        assertSame( "mineInteraction.getExperiment()", experiment, mineInteraction.getExperiment() );
        assertEquals( "mineInteraction.getPubmedId()", "testMineInteractionPubmedId", mineInteraction.getPubmedId() );
        assertEquals( "mineInteraction.getShortLabel1()", "testMineInteractionShortLabel1", mineInteraction.getShortLabel1() );
        assertEquals( "mineInteraction.getShortLabel2()", "testMineInteractionShortLabel2", mineInteraction.getShortLabel2() );
        assertSame( "mineInteraction.getDetectionMethod()", detectionMethod, mineInteraction.getDetectionMethod() );
    }

    public void testHashCode7() throws Throwable {
        CvTopic detectionMethod = new CvTopic( new Institution( "testMineInteraction\nShortLabel" ), "testMineInteractionShortLabel" );
        MineInteractionPk pk = new MineInteractionPk( null, new ProteinImpl( new Institution( "testMineInteractionShortLabel1" ), new BioSource( new Institution( "testMineInteractionShortLabel" ), "testMineInteractionShortLabel", "-68833" ), "testMineInteractionShortLabel" ), new InteractionImpl( new ArrayList( 100 ), ( CvInteractionType ) null, new CvInteractorType( new Institution( "testMineInteractionShortLabel2" ), "testMineInteractionShortLabel" ), "testMineInteractionShortLabel", new Institution( "testMineInteraction\rShortLabel" ) ) );
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setPubmedId( "testMineInteractionPubmedId" );
        mineInteraction.setShortLabel2( "testMineInteractionShortLabel2" );
        mineInteraction.setDetectionMethod( detectionMethod );
        mineInteraction.setShortLabel1( "testMineInteractionShortLabel1" );
        mineInteraction.setTaxid( "testMineInteractionTaxid" );
        mineInteraction.setPk( pk );
        int result = mineInteraction.hashCode();
        assertEquals( "result", -855190603, result );
        assertSame( "mineInteraction.getPk()", pk, mineInteraction.getPk() );
        assertEquals( "mineInteraction.getTaxid()", "testMineInteractionTaxid", mineInteraction.getTaxid() );
        assertNull( "mineInteraction.getExperiment()", mineInteraction.getExperiment() );
        assertEquals( "mineInteraction.getPubmedId()", "testMineInteractionPubmedId", mineInteraction.getPubmedId() );
        assertEquals( "mineInteraction.getShortLabel1()", "testMineInteractionShortLabel1", mineInteraction.getShortLabel1() );
        assertEquals( "mineInteraction.getShortLabel2()", "testMineInteractionShortLabel2", mineInteraction.getShortLabel2() );
        assertSame( "mineInteraction.getDetectionMethod()", detectionMethod, mineInteraction.getDetectionMethod() );
    }

    public void testHashCode8() throws Throwable {
        CvTopic detectionMethod = new CvTopic( new Institution( "testMineInteractionShortLabel" ), "testMineInteractionShortLabel" );
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setShortLabel2( "testMineInteractionShortLabel2" );
        mineInteraction.setDetectionMethod( detectionMethod );
        mineInteraction.setShortLabel1( "testMineInteractionShortLabel1" );
        mineInteraction.setTaxid( "testMineInteractionTaxid" );
        int result = mineInteraction.hashCode();
        assertEquals( "result", 68445327, result );
        assertNull( "mineInteraction.getPk()", mineInteraction.getPk() );
        assertEquals( "mineInteraction.getTaxid()", "testMineInteractionTaxid", mineInteraction.getTaxid() );
        assertNull( "mineInteraction.getExperiment()", mineInteraction.getExperiment() );
        assertNull( "mineInteraction.getPubmedId()", mineInteraction.getPubmedId() );
        assertEquals( "mineInteraction.getShortLabel1()", "testMineInteractionShortLabel1", mineInteraction.getShortLabel1() );
        assertEquals( "mineInteraction.getShortLabel2()", "testMineInteractionShortLabel2", mineInteraction.getShortLabel2() );
        assertSame( "mineInteraction.getDetectionMethod()", detectionMethod, mineInteraction.getDetectionMethod() );
    }

    public void testHashCode9() throws Throwable {
        CvTopic detectionMethod = new CvTopic( new Institution( "testMineInteractionShortLabel" ), "testMineInteractionShortLabel" );
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setDetectionMethod( detectionMethod );
        int result = mineInteraction.hashCode();
        assertEquals( "result", -655717017, result );
        assertNull( "mineInteraction.getPk()", mineInteraction.getPk() );
        assertNull( "mineInteraction.getTaxid()", mineInteraction.getTaxid() );
        assertNull( "mineInteraction.getExperiment()", mineInteraction.getExperiment() );
        assertNull( "mineInteraction.getPubmedId()", mineInteraction.getPubmedId() );
        assertNull( "mineInteraction.getShortLabel1()", mineInteraction.getShortLabel1() );
        assertNull( "mineInteraction.getShortLabel2()", mineInteraction.getShortLabel2() );
        assertSame( "mineInteraction.getDetectionMethod()", detectionMethod, mineInteraction.getDetectionMethod() );
    }

    public void testHashCode10() throws Throwable {
        MineInteractionPk pk = new MineInteractionPk();
        CvTopic detectionMethod = new CvTopic( new Institution( "testMineInteractionShortLabel" ), "testMineInteractionShortLabel" );
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setShortLabel2( "testMineInteractionShortLabel2" );
        mineInteraction.setDetectionMethod( detectionMethod );
        mineInteraction.setTaxid( "testMineInteractionTaxid" );
        mineInteraction.setPk( pk );
        int result = mineInteraction.hashCode();
        assertEquals( "result", 1106820699, result );
        assertSame( "mineInteraction.getPk()", pk, mineInteraction.getPk() );
        assertEquals( "mineInteraction.getTaxid()", "testMineInteractionTaxid", mineInteraction.getTaxid() );
        assertNull( "mineInteraction.getExperiment()", mineInteraction.getExperiment() );
        assertNull( "mineInteraction.getPubmedId()", mineInteraction.getPubmedId() );
        assertNull( "mineInteraction.getShortLabel1()", mineInteraction.getShortLabel1() );
        assertEquals( "mineInteraction.getShortLabel2()", "testMineInteractionShortLabel2", mineInteraction.getShortLabel2() );
        assertSame( "mineInteraction.getDetectionMethod()", detectionMethod, mineInteraction.getDetectionMethod() );
    }

    public void testHashCode11() throws Throwable {
        MineInteractionPk pk = new MineInteractionPk();
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setShortLabel2( "testMineInteractionShortLabel2" );
        mineInteraction.setPk( pk );
        int result = mineInteraction.hashCode();
        assertEquals( "result", 576913037, result );
        assertSame( "mineInteraction.getPk()", pk, mineInteraction.getPk() );
        assertNull( "mineInteraction.getTaxid()", mineInteraction.getTaxid() );
        assertNull( "mineInteraction.getExperiment()", mineInteraction.getExperiment() );
        assertNull( "mineInteraction.getPubmedId()", mineInteraction.getPubmedId() );
        assertNull( "mineInteraction.getShortLabel1()", mineInteraction.getShortLabel1() );
        assertEquals( "mineInteraction.getShortLabel2()", "testMineInteractionShortLabel2", mineInteraction.getShortLabel2() );
        assertNull( "mineInteraction.getDetectionMethod()", mineInteraction.getDetectionMethod() );
    }

    public void testHashCode12() throws Throwable {
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setShortLabel2( "testMineInteractionShortLabel2" );
        mineInteraction.setShortLabel1( "testMineInteractionShortLabel1" );
        mineInteraction.setTaxid( "testMineInteractionTaxid" );
        int result = mineInteraction.hashCode();
        assertEquals( "result", 724162344, result );
        assertNull( "mineInteraction.getPk()", mineInteraction.getPk() );
        assertEquals( "mineInteraction.getTaxid()", "testMineInteractionTaxid", mineInteraction.getTaxid() );
        assertNull( "mineInteraction.getExperiment()", mineInteraction.getExperiment() );
        assertNull( "mineInteraction.getPubmedId()", mineInteraction.getPubmedId() );
        assertEquals( "mineInteraction.getShortLabel1()", "testMineInteractionShortLabel1", mineInteraction.getShortLabel1() );
        assertEquals( "mineInteraction.getShortLabel2()", "testMineInteractionShortLabel2", mineInteraction.getShortLabel2() );
        assertNull( "mineInteraction.getDetectionMethod()", mineInteraction.getDetectionMethod() );
    }

    public void testHashCode13() throws Throwable {
        CvTopic detectionMethod = new CvTopic( new Institution( "testMineInteractionShortLabel" ), "testMineInteractionShortLabel" );
        MineInteractionPk pk = new MineInteractionPk();
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setDetectionMethod( detectionMethod );
        mineInteraction.setPk( pk );
        int result = mineInteraction.hashCode();
        assertEquals( "result", -655717017, result );
        assertSame( "mineInteraction.getPk()", pk, mineInteraction.getPk() );
        assertNull( "mineInteraction.getTaxid()", mineInteraction.getTaxid() );
        assertNull( "mineInteraction.getExperiment()", mineInteraction.getExperiment() );
        assertNull( "mineInteraction.getPubmedId()", mineInteraction.getPubmedId() );
        assertNull( "mineInteraction.getShortLabel1()", mineInteraction.getShortLabel1() );
        assertNull( "mineInteraction.getShortLabel2()", mineInteraction.getShortLabel2() );
        assertSame( "mineInteraction.getDetectionMethod()", detectionMethod, mineInteraction.getDetectionMethod() );
    }

    public void testHashCode14() throws Throwable {
        MineInteractionPk pk = new MineInteractionPk();
        CvTopic detectionMethod = new CvTopic( new Institution( "testMineInteractionShortLabel" ), "testMineInteractionShortLabel" );
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setShortLabel2( "testMineInteractionShortLabel2" );
        mineInteraction.setDetectionMethod( detectionMethod );
        mineInteraction.setShortLabel1( "testMineInteractionShortLabel1" );
        mineInteraction.setTaxid( "testMineInteractionTaxid" );
        mineInteraction.setPk( pk );
        int result = mineInteraction.hashCode();
        assertEquals( "result", 68445327, result );
        assertSame( "mineInteraction.getPk()", pk, mineInteraction.getPk() );
        assertEquals( "mineInteraction.getTaxid()", "testMineInteractionTaxid", mineInteraction.getTaxid() );
        assertNull( "mineInteraction.getExperiment()", mineInteraction.getExperiment() );
        assertNull( "mineInteraction.getPubmedId()", mineInteraction.getPubmedId() );
        assertEquals( "mineInteraction.getShortLabel1()", "testMineInteractionShortLabel1", mineInteraction.getShortLabel1() );
        assertEquals( "mineInteraction.getShortLabel2()", "testMineInteractionShortLabel2", mineInteraction.getShortLabel2() );
        assertSame( "mineInteraction.getDetectionMethod()", detectionMethod, mineInteraction.getDetectionMethod() );
    }

    public void testHashCode15() throws Throwable {
        BioSource source = new BioSource( new Institution( "testMineInteractionShortLabel" ), "testMineInteractionShortLabel", "-68833" );
        ProteinImpl protein2 = new ProteinImpl( new Institution( "testMineInteractionShortLabel1" ), source, "testMineInteractionShortLabel" );
        Experiment experiment = new Experiment( new Institution( "testMineInteraction\nShortLabel" ), "testMineInteractionShortLabel", source );
        CvTopic detectionMethod = new CvTopic( new Institution( "testMineInteraction\tShortLabel" ), "testMineInteractionShortLabel" );
        MineInteractionPk pk = new MineInteractionPk( null, protein2, new InteractionImpl( new ArrayList( 100 ), ( CvInteractionType ) null, new CvInteractorType( new Institution( "testMineInteractionShortLabel2" ), "testMineInteractionShortLabel" ), "testMineInteractionShortLabel", new Institution( "testMineInteraction\rShortLabel" ) ) );
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setShortLabel2( "testMineInteractionShortLabel2" );
        mineInteraction.setDetectionMethod( detectionMethod );
        mineInteraction.setExperiment( experiment );
        mineInteraction.setShortLabel1( "testMineInteractionShortLabel1" );
        mineInteraction.setTaxid( "testMineInteractionTaxid" );
        mineInteraction.setPk( pk );
        int result = mineInteraction.hashCode();
        assertEquals( "result", -987512369, result );
        assertSame( "mineInteraction.getPk()", pk, mineInteraction.getPk() );
        assertEquals( "mineInteraction.getTaxid()", "testMineInteractionTaxid", mineInteraction.getTaxid() );
        assertSame( "mineInteraction.getExperiment()", experiment, mineInteraction.getExperiment() );
        assertNull( "mineInteraction.getPubmedId()", mineInteraction.getPubmedId() );
        assertEquals( "mineInteraction.getShortLabel1()", "testMineInteractionShortLabel1", mineInteraction.getShortLabel1() );
        assertEquals( "mineInteraction.getShortLabel2()", "testMineInteractionShortLabel2", mineInteraction.getShortLabel2() );
        assertSame( "mineInteraction.getDetectionMethod()", detectionMethod, mineInteraction.getDetectionMethod() );
    }

    public void testHashCode16() throws Throwable {
        BioSource source = new BioSource( new Institution( "testMineInteractionShortLabel" ), "testMineInteractionShortLabel", "-68833" );
        ProteinImpl protein2 = new ProteinImpl( new Institution( "testMineInteractionShortLabel1" ), source, "testMineInteractionShortLabel" );
        Experiment experiment = new Experiment( new Institution( "testMineInteraction\nShortLabel" ), "testMineInteractionShortLabel", source );
        CvTopic detectionMethod = new CvTopic( new Institution( "testMineInteraction\tShortLabel" ), "testMineInteractionShortLabel" );
        MineInteractionPk pk = new MineInteractionPk( null, protein2, new InteractionImpl( new ArrayList( 100 ), ( CvInteractionType ) null, new CvInteractorType( new Institution( "testMineInteractionShortLabel2" ), "testMineInteractionShortLabel" ), "testMineInteractionShortLabel", new Institution( "testMineInteraction\rShortLabel" ) ) );
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setPubmedId( "testMineInteractionPubmedId" );
        mineInteraction.setShortLabel2( "testMineInteractionShortLabel2" );
        mineInteraction.setDetectionMethod( detectionMethod );
        mineInteraction.setExperiment( experiment );
        mineInteraction.setTaxid( "testMineInteractionTaxid" );
        mineInteraction.setPk( pk );
        int result = mineInteraction.hashCode();
        assertEquals( "result", -1862115662, result );
        assertSame( "mineInteraction.getPk()", pk, mineInteraction.getPk() );
        assertEquals( "mineInteraction.getTaxid()", "testMineInteractionTaxid", mineInteraction.getTaxid() );
        assertSame( "mineInteraction.getExperiment()", experiment, mineInteraction.getExperiment() );
        assertEquals( "mineInteraction.getPubmedId()", "testMineInteractionPubmedId", mineInteraction.getPubmedId() );
        assertNull( "mineInteraction.getShortLabel1()", mineInteraction.getShortLabel1() );
        assertEquals( "mineInteraction.getShortLabel2()", "testMineInteractionShortLabel2", mineInteraction.getShortLabel2() );
        assertSame( "mineInteraction.getDetectionMethod()", detectionMethod, mineInteraction.getDetectionMethod() );
    }

    public void testHashCode17() throws Throwable {
        MineInteractionPk pk = new MineInteractionPk();
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setShortLabel2( "testMineInteractionShortLabel2" );
        mineInteraction.setShortLabel1( "testMineInteractionShortLabel1" );
        mineInteraction.setPk( pk );
        int result = mineInteraction.hashCode();
        assertEquals( "result", -461462335, result );
        assertSame( "mineInteraction.getPk()", pk, mineInteraction.getPk() );
        assertNull( "mineInteraction.getTaxid()", mineInteraction.getTaxid() );
        assertNull( "mineInteraction.getExperiment()", mineInteraction.getExperiment() );
        assertNull( "mineInteraction.getPubmedId()", mineInteraction.getPubmedId() );
        assertEquals( "mineInteraction.getShortLabel1()", "testMineInteractionShortLabel1", mineInteraction.getShortLabel1() );
        assertEquals( "mineInteraction.getShortLabel2()", "testMineInteractionShortLabel2", mineInteraction.getShortLabel2() );
        assertNull( "mineInteraction.getDetectionMethod()", mineInteraction.getDetectionMethod() );
    }

    public void testHashCode18() throws Throwable {
        BioSource source = new BioSource( new Institution( "testMineInteractionShortLabel" ), "testMineInteractionShortLabel", "-68833" );
        ProteinImpl protein2 = new ProteinImpl( new Institution( "testMineInteractionShortLabel1" ), source, "testMineInteractionShortLabel" );
        Experiment experiment = new Experiment( new Institution( "testMineInteraction\nShortLabel" ), "testMineInteractionShortLabel", source );
        CvTopic detectionMethod = new CvTopic( new Institution( "testMineInteraction\tShortLabel" ), "testMineInteractionShortLabel" );
        MineInteractionPk pk = new MineInteractionPk( null, protein2, new InteractionImpl( new ArrayList( 100 ), ( CvInteractionType ) null, new CvInteractorType( new Institution( "testMineInteractionShortLabel2" ), "testMineInteractionShortLabel" ), "testMineInteractionShortLabel", new Institution( "testMineInteraction\rShortLabel" ) ) );
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setPubmedId( "testMineInteractionPubmedId" );
        mineInteraction.setDetectionMethod( detectionMethod );
        mineInteraction.setExperiment( experiment );
        mineInteraction.setShortLabel1( "testMineInteractionShortLabel1" );
        mineInteraction.setTaxid( "testMineInteractionTaxid" );
        mineInteraction.setPk( pk );
        int result = mineInteraction.hashCode();
        assertEquals( "result", 817563225, result );
        assertSame( "mineInteraction.getPk()", pk, mineInteraction.getPk() );
        assertEquals( "mineInteraction.getTaxid()", "testMineInteractionTaxid", mineInteraction.getTaxid() );
        assertSame( "mineInteraction.getExperiment()", experiment, mineInteraction.getExperiment() );
        assertEquals( "mineInteraction.getPubmedId()", "testMineInteractionPubmedId", mineInteraction.getPubmedId() );
        assertEquals( "mineInteraction.getShortLabel1()", "testMineInteractionShortLabel1", mineInteraction.getShortLabel1() );
        assertNull( "mineInteraction.getShortLabel2()", mineInteraction.getShortLabel2() );
        assertSame( "mineInteraction.getDetectionMethod()", detectionMethod, mineInteraction.getDetectionMethod() );
    }

    public void testHashCode19() throws Throwable {
        MineInteractionPk pk = new MineInteractionPk();
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setShortLabel1( "testMineInteractionShortLabel1" );
        mineInteraction.setPk( pk );
        int result = mineInteraction.hashCode();
        assertEquals( "result", -1038375372, result );
        assertSame( "mineInteraction.getPk()", pk, mineInteraction.getPk() );
        assertNull( "mineInteraction.getTaxid()", mineInteraction.getTaxid() );
        assertNull( "mineInteraction.getExperiment()", mineInteraction.getExperiment() );
        assertNull( "mineInteraction.getPubmedId()", mineInteraction.getPubmedId() );
        assertEquals( "mineInteraction.getShortLabel1()", "testMineInteractionShortLabel1", mineInteraction.getShortLabel1() );
        assertNull( "mineInteraction.getShortLabel2()", mineInteraction.getShortLabel2() );
        assertNull( "mineInteraction.getDetectionMethod()", mineInteraction.getDetectionMethod() );
    }

    public void testHashCode20() throws Throwable {
        BioSource source = new BioSource( new Institution( "testMineInteractionShortLabel" ), "testMineInteractionShortLabel", "-68833" );
        ProteinImpl protein2 = new ProteinImpl( new Institution( "testMineInteractionShortLabel1" ), source, "testMineInteractionShortLabel" );
        Experiment experiment = new Experiment( new Institution( "testMineInteraction\nShortLabel" ), "testMineInteractionShortLabel", source );
        CvTopic detectionMethod = new CvTopic( new Institution( "testMineInteraction\tShortLabel" ), "testMineInteractionShortLabel" );
        MineInteractionPk pk = new MineInteractionPk( null, protein2, new InteractionImpl( new ArrayList( 100 ), ( CvInteractionType ) null, new CvInteractorType( new Institution( "testMineInteractionShortLabel2" ), "testMineInteractionShortLabel" ), "testMineInteractionShortLabel", new Institution( "testMineInteraction\rShortLabel" ) ) );
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setPubmedId( "testMineInteractionPubmedId" );
        mineInteraction.setShortLabel2( "testMineInteractionShortLabel2" );
        mineInteraction.setDetectionMethod( detectionMethod );
        mineInteraction.setExperiment( experiment );
        mineInteraction.setShortLabel1( "testMineInteractionShortLabel1" );
        mineInteraction.setPk( pk );
        int result = mineInteraction.hashCode();
        assertEquals( "result", 208851583, result );
        assertSame( "mineInteraction.getPk()", pk, mineInteraction.getPk() );
        assertNull( "mineInteraction.getTaxid()", mineInteraction.getTaxid() );
        assertSame( "mineInteraction.getExperiment()", experiment, mineInteraction.getExperiment() );
        assertEquals( "mineInteraction.getPubmedId()", "testMineInteractionPubmedId", mineInteraction.getPubmedId() );
        assertEquals( "mineInteraction.getShortLabel1()", "testMineInteractionShortLabel1", mineInteraction.getShortLabel1() );
        assertEquals( "mineInteraction.getShortLabel2()", "testMineInteractionShortLabel2", mineInteraction.getShortLabel2() );
        assertSame( "mineInteraction.getDetectionMethod()", detectionMethod, mineInteraction.getDetectionMethod() );
    }

    public void testHashCode21() throws Throwable {
        MineInteractionPk pk = new MineInteractionPk();
        CvTopic detectionMethod = new CvTopic( new Institution( "testMineInteractionShortLabel" ), "testMineInteractionShortLabel" );
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setDetectionMethod( detectionMethod );
        mineInteraction.setShortLabel1( "testMineInteractionShortLabel1" );
        mineInteraction.setTaxid( "testMineInteractionTaxid" );
        mineInteraction.setPk( pk );
        int result = mineInteraction.hashCode();
        assertEquals( "result", -508467710, result );
        assertSame( "mineInteraction.getPk()", pk, mineInteraction.getPk() );
        assertEquals( "mineInteraction.getTaxid()", "testMineInteractionTaxid", mineInteraction.getTaxid() );
        assertNull( "mineInteraction.getExperiment()", mineInteraction.getExperiment() );
        assertNull( "mineInteraction.getPubmedId()", mineInteraction.getPubmedId() );
        assertEquals( "mineInteraction.getShortLabel1()", "testMineInteractionShortLabel1", mineInteraction.getShortLabel1() );
        assertNull( "mineInteraction.getShortLabel2()", mineInteraction.getShortLabel2() );
        assertSame( "mineInteraction.getDetectionMethod()", detectionMethod, mineInteraction.getDetectionMethod() );
    }

    public void testHashCode22() throws Throwable {
        BioSource source = new BioSource( new Institution( "testMineInteractionShortLabel" ), "testMineInteractionShortLabel", "-68833" );
        ProteinImpl protein2 = new ProteinImpl( new Institution( "testMineInteractionShortLabel1" ), source, "testMineInteractionShortLabel" );
        Experiment experiment = new Experiment( new Institution( "testMineInteraction\nShortLabel" ), "testMineInteractionShortLabel", source );
        MineInteractionPk pk = new MineInteractionPk( null, protein2, new InteractionImpl( new ArrayList( 100 ), ( CvInteractionType ) null, new CvInteractorType( new Institution( "testMineInteractionShortLabel2" ), "testMineInteractionShortLabel" ), "testMineInteractionShortLabel", new Institution( "testMineInteraction\rShortLabel" ) ) );
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setPubmedId( "testMineInteractionPubmedId" );
        mineInteraction.setShortLabel2( "testMineInteractionShortLabel2" );
        mineInteraction.setExperiment( experiment );
        mineInteraction.setShortLabel1( "testMineInteractionShortLabel1" );
        mineInteraction.setTaxid( "testMineInteractionTaxid" );
        mineInteraction.setPk( pk );
        int result = mineInteraction.hashCode();
        assertEquals( "result", 2050193279, result );
        assertSame( "mineInteraction.getPk()", pk, mineInteraction.getPk() );
        assertEquals( "mineInteraction.getTaxid()", "testMineInteractionTaxid", mineInteraction.getTaxid() );
        assertSame( "mineInteraction.getExperiment()", experiment, mineInteraction.getExperiment() );
        assertEquals( "mineInteraction.getPubmedId()", "testMineInteractionPubmedId", mineInteraction.getPubmedId() );
        assertEquals( "mineInteraction.getShortLabel1()", "testMineInteractionShortLabel1", mineInteraction.getShortLabel1() );
        assertEquals( "mineInteraction.getShortLabel2()", "testMineInteractionShortLabel2", mineInteraction.getShortLabel2() );
        assertNull( "mineInteraction.getDetectionMethod()", mineInteraction.getDetectionMethod() );
    }

    public void testHashCode23() throws Throwable {
        MineInteraction mineInteraction = new MineInteraction();
        int result = mineInteraction.hashCode();
        assertEquals( "result", 0, result );
        assertNull( "mineInteraction.getPk()", mineInteraction.getPk() );
        assertNull( "mineInteraction.getTaxid()", mineInteraction.getTaxid() );
        assertNull( "mineInteraction.getExperiment()", mineInteraction.getExperiment() );
        assertNull( "mineInteraction.getPubmedId()", mineInteraction.getPubmedId() );
        assertNull( "mineInteraction.getShortLabel1()", mineInteraction.getShortLabel1() );
        assertNull( "mineInteraction.getShortLabel2()", mineInteraction.getShortLabel2() );
        assertNull( "mineInteraction.getDetectionMethod()", mineInteraction.getDetectionMethod() );
    }

    public void testHashCode24() throws Throwable {
        MineInteractionPk pk = new MineInteractionPk();
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setPubmedId( "testMineInteractionPubmedId" );
        mineInteraction.setShortLabel2( "testMineInteractionShortLabel2" );
        mineInteraction.setShortLabel1( "testMineInteractionShortLabel1" );
        mineInteraction.setTaxid( "testMineInteractionTaxid" );
        mineInteraction.setPk( pk );
        int result = mineInteraction.hashCode();
        assertEquals( "result", -1188816321, result );
        assertSame( "mineInteraction.getPk()", pk, mineInteraction.getPk() );
        assertEquals( "mineInteraction.getTaxid()", "testMineInteractionTaxid", mineInteraction.getTaxid() );
        assertNull( "mineInteraction.getExperiment()", mineInteraction.getExperiment() );
        assertEquals( "mineInteraction.getPubmedId()", "testMineInteractionPubmedId", mineInteraction.getPubmedId() );
        assertEquals( "mineInteraction.getShortLabel1()", "testMineInteractionShortLabel1", mineInteraction.getShortLabel1() );
        assertEquals( "mineInteraction.getShortLabel2()", "testMineInteractionShortLabel2", mineInteraction.getShortLabel2() );
        assertNull( "mineInteraction.getDetectionMethod()", mineInteraction.getDetectionMethod() );
    }

    public void testHashCode25() throws Throwable {
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setShortLabel2( "testMineInteractionShortLabel2" );
        mineInteraction.setTaxid( "testMineInteractionTaxid" );
        int result = mineInteraction.hashCode();
        assertEquals( "result", 1762537716, result );
        assertNull( "mineInteraction.getPk()", mineInteraction.getPk() );
        assertEquals( "mineInteraction.getTaxid()", "testMineInteractionTaxid", mineInteraction.getTaxid() );
        assertNull( "mineInteraction.getExperiment()", mineInteraction.getExperiment() );
        assertNull( "mineInteraction.getPubmedId()", mineInteraction.getPubmedId() );
        assertNull( "mineInteraction.getShortLabel1()", mineInteraction.getShortLabel1() );
        assertEquals( "mineInteraction.getShortLabel2()", "testMineInteractionShortLabel2", mineInteraction.getShortLabel2() );
        assertNull( "mineInteraction.getDetectionMethod()", mineInteraction.getDetectionMethod() );
    }

    public void testHashCode26() throws Throwable {
        BioSource source = new BioSource( new Institution( "testMineInteractionShortLabel" ), "testMineInteractionShortLabel", "-68833" );
        ProteinImpl protein2 = new ProteinImpl( new Institution( "testMineInteractionShortLabel1" ), source, "testMineInteractionShortLabel" );
        Experiment experiment = new Experiment( new Institution( "testMineInteraction\nShortLabel" ), "testMineInteractionShortLabel", source );
        CvTopic detectionMethod = new CvTopic( new Institution( "testMineInteraction\tShortLabel" ), "testMineInteractionShortLabel" );
        MineInteractionPk pk = new MineInteractionPk( null, protein2, new InteractionImpl( new ArrayList( 100 ), ( CvInteractionType ) null, new CvInteractorType( new Institution( "testMineInteractionShortLabel2" ), "testMineInteractionShortLabel" ), "testMineInteractionShortLabel", new Institution( "testMineInteraction\rShortLabel" ) ) );
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setPubmedId( "testMineInteractionPubmedId" );
        mineInteraction.setShortLabel2( "testMineInteractionShortLabel2" );
        mineInteraction.setDetectionMethod( detectionMethod );
        mineInteraction.setExperiment( experiment );
        mineInteraction.setShortLabel1( "testMineInteractionShortLabel1" );
        mineInteraction.setTaxid( "testMineInteractionTaxid" );
        mineInteraction.setPk( pk );
        int result = mineInteraction.hashCode();
        assertEquals( "result", 1394476262, result );
        assertSame( "mineInteraction.getPk()", pk, mineInteraction.getPk() );
        assertEquals( "mineInteraction.getTaxid()", "testMineInteractionTaxid", mineInteraction.getTaxid() );
        assertSame( "mineInteraction.getExperiment()", experiment, mineInteraction.getExperiment() );
        assertEquals( "mineInteraction.getPubmedId()", "testMineInteractionPubmedId", mineInteraction.getPubmedId() );
        assertEquals( "mineInteraction.getShortLabel1()", "testMineInteractionShortLabel1", mineInteraction.getShortLabel1() );
        assertEquals( "mineInteraction.getShortLabel2()", "testMineInteractionShortLabel2", mineInteraction.getShortLabel2() );
        assertSame( "mineInteraction.getDetectionMethod()", detectionMethod, mineInteraction.getDetectionMethod() );
    }

    public void testHashCode27() throws Throwable {
        CvTopic detectionMethod = new CvTopic( new Institution( "testMineInteractionShortLabel1" ), "testMineInteractionShortLabel" );
        Experiment experiment = new Experiment( new Institution( "testMineInteractionShortLabel2" ), "testMineInteractionShortLabel", new BioSource( new Institution( "testMineInteractionShortLabel" ), "testMineInteractionShortLabel", "-68833" ) );
        MineInteractionPk pk = new MineInteractionPk();
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setPubmedId( "testMineInteractionPubmedId" );
        mineInteraction.setShortLabel2( "testMineInteractionShortLabel2" );
        mineInteraction.setDetectionMethod( detectionMethod );
        mineInteraction.setExperiment( experiment );
        mineInteraction.setPk( pk );
        int result = mineInteraction.hashCode();
        assertEquals( "result", 257884220, result );
        assertSame( "mineInteraction.getPk()", pk, mineInteraction.getPk() );
        assertNull( "mineInteraction.getTaxid()", mineInteraction.getTaxid() );
        assertSame( "mineInteraction.getExperiment()", experiment, mineInteraction.getExperiment() );
        assertEquals( "mineInteraction.getPubmedId()", "testMineInteractionPubmedId", mineInteraction.getPubmedId() );
        assertNull( "mineInteraction.getShortLabel1()", mineInteraction.getShortLabel1() );
        assertEquals( "mineInteraction.getShortLabel2()", "testMineInteractionShortLabel2", mineInteraction.getShortLabel2() );
        assertSame( "mineInteraction.getDetectionMethod()", detectionMethod, mineInteraction.getDetectionMethod() );
    }

    public void testHashCode28() throws Throwable {
        MineInteractionPk pk = new MineInteractionPk();
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setShortLabel1( "testMineInteractionShortLabel1" );
        mineInteraction.setTaxid( "testMineInteractionTaxid" );
        mineInteraction.setPk( pk );
        int result = mineInteraction.hashCode();
        assertEquals( "result", 147249307, result );
        assertSame( "mineInteraction.getPk()", pk, mineInteraction.getPk() );
        assertEquals( "mineInteraction.getTaxid()", "testMineInteractionTaxid", mineInteraction.getTaxid() );
        assertNull( "mineInteraction.getExperiment()", mineInteraction.getExperiment() );
        assertNull( "mineInteraction.getPubmedId()", mineInteraction.getPubmedId() );
        assertEquals( "mineInteraction.getShortLabel1()", "testMineInteractionShortLabel1", mineInteraction.getShortLabel1() );
        assertNull( "mineInteraction.getShortLabel2()", mineInteraction.getShortLabel2() );
        assertNull( "mineInteraction.getDetectionMethod()", mineInteraction.getDetectionMethod() );
    }

    public void testHashCode29() throws Throwable {
        MineInteractionPk pk = new MineInteractionPk();
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setShortLabel2( "testMineInteractionShortLabel2" );
        mineInteraction.setWeight( 100.0 );
        mineInteraction.setShortLabel1( "testMineInteractionShortLabel1" );
        mineInteraction.setTaxid( "testMineInteractionTaxid" );
        mineInteraction.setPk( pk );
        int result = mineInteraction.hashCode();
        assertEquals( "result", -1761421528, result );
        assertSame( "mineInteraction.getPk()", pk, mineInteraction.getPk() );
        assertEquals( "mineInteraction.getTaxid()", "testMineInteractionTaxid", mineInteraction.getTaxid() );
        assertNull( "mineInteraction.getExperiment()", mineInteraction.getExperiment() );
        assertNull( "mineInteraction.getPubmedId()", mineInteraction.getPubmedId() );
        assertEquals( "mineInteraction.getShortLabel1()", "testMineInteractionShortLabel1", mineInteraction.getShortLabel1() );
        assertEquals( "mineInteraction.getShortLabel2()", "testMineInteractionShortLabel2", mineInteraction.getShortLabel2() );
        assertNull( "mineInteraction.getDetectionMethod()", mineInteraction.getDetectionMethod() );
    }

    public void testHashCode30() throws Throwable {
        MineInteractionPk pk = new MineInteractionPk();
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setPubmedId( "testMineInteractionPubmedId" );
        mineInteraction.setShortLabel2( "testMineInteractionShortLabel2" );
        mineInteraction.setWeight( 100.0 );
        mineInteraction.setShortLabel1( "testMineInteractionShortLabel1" );
        mineInteraction.setTaxid( "testMineInteractionTaxid" );
        mineInteraction.setPk( pk );
        int result = mineInteraction.hashCode();
        assertEquals( "result", 620567103, result );
        assertSame( "mineInteraction.getPk()", pk, mineInteraction.getPk() );
        assertEquals( "mineInteraction.getTaxid()", "testMineInteractionTaxid", mineInteraction.getTaxid() );
        assertNull( "mineInteraction.getExperiment()", mineInteraction.getExperiment() );
        assertEquals( "mineInteraction.getPubmedId()", "testMineInteractionPubmedId", mineInteraction.getPubmedId() );
        assertEquals( "mineInteraction.getShortLabel1()", "testMineInteractionShortLabel1", mineInteraction.getShortLabel1() );
        assertEquals( "mineInteraction.getShortLabel2()", "testMineInteractionShortLabel2", mineInteraction.getShortLabel2() );
        assertNull( "mineInteraction.getDetectionMethod()", mineInteraction.getDetectionMethod() );
    }

    public void testHashCode31() throws Throwable {
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setPubmedId( "testMineInteractionPubmedId" );
        mineInteraction.setShortLabel2( "testMineInteractionShortLabel2" );
        mineInteraction.setWeight( 100.0 );
        mineInteraction.setShortLabel1( "testMineInteractionShortLabel1" );
        mineInteraction.setTaxid( "testMineInteractionTaxid" );
        int result = mineInteraction.hashCode();
        assertEquals( "result", 620567103, result );
        assertNull( "mineInteraction.getPk()", mineInteraction.getPk() );
        assertEquals( "mineInteraction.getTaxid()", "testMineInteractionTaxid", mineInteraction.getTaxid() );
        assertNull( "mineInteraction.getExperiment()", mineInteraction.getExperiment() );
        assertEquals( "mineInteraction.getPubmedId()", "testMineInteractionPubmedId", mineInteraction.getPubmedId() );
        assertEquals( "mineInteraction.getShortLabel1()", "testMineInteractionShortLabel1", mineInteraction.getShortLabel1() );
        assertEquals( "mineInteraction.getShortLabel2()", "testMineInteractionShortLabel2", mineInteraction.getShortLabel2() );
        assertNull( "mineInteraction.getDetectionMethod()", mineInteraction.getDetectionMethod() );
    }

    public void testHashCode32() throws Throwable {
        CvTopic detectionMethod = new CvTopic( new Institution( "testMineInteractionShortLabel1" ), "testMineInteractionShortLabel" );
        Experiment experiment = new Experiment( new Institution( "testMineInteractionShortLabel2" ), "testMineInteractionShortLabel", new BioSource( new Institution( "testMineInteractionShortLabel" ), "testMineInteractionShortLabel", "-68833" ) );
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setPubmedId( "testMineInteractionPubmedId" );
        mineInteraction.setShortLabel2( "testMineInteractionShortLabel2" );
        mineInteraction.setDetectionMethod( detectionMethod );
        mineInteraction.setWeight( 100.0 );
        mineInteraction.setExperiment( experiment );
        int result = mineInteraction.hashCode();
        assertEquals( "result", 2067267644, result );
        assertNull( "mineInteraction.getPk()", mineInteraction.getPk() );
        assertNull( "mineInteraction.getTaxid()", mineInteraction.getTaxid() );
        assertSame( "mineInteraction.getExperiment()", experiment, mineInteraction.getExperiment() );
        assertEquals( "mineInteraction.getPubmedId()", "testMineInteractionPubmedId", mineInteraction.getPubmedId() );
        assertNull( "mineInteraction.getShortLabel1()", mineInteraction.getShortLabel1() );
        assertEquals( "mineInteraction.getShortLabel2()", "testMineInteractionShortLabel2", mineInteraction.getShortLabel2() );
        assertSame( "mineInteraction.getDetectionMethod()", detectionMethod, mineInteraction.getDetectionMethod() );
    }

    public void testHashCode33() throws Throwable {
        MineInteractionPk pk = new MineInteractionPk();
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setPubmedId( "testMineInteractionPubmedId" );
        mineInteraction.setWeight( 100.0 );
        mineInteraction.setShortLabel1( "testMineInteractionShortLabel1" );
        mineInteraction.setTaxid( "testMineInteractionTaxid" );
        mineInteraction.setPk( pk );
        int result = mineInteraction.hashCode();
        assertEquals( "result", 43654066, result );
        assertSame( "mineInteraction.getPk()", pk, mineInteraction.getPk() );
        assertEquals( "mineInteraction.getTaxid()", "testMineInteractionTaxid", mineInteraction.getTaxid() );
        assertNull( "mineInteraction.getExperiment()", mineInteraction.getExperiment() );
        assertEquals( "mineInteraction.getPubmedId()", "testMineInteractionPubmedId", mineInteraction.getPubmedId() );
        assertEquals( "mineInteraction.getShortLabel1()", "testMineInteractionShortLabel1", mineInteraction.getShortLabel1() );
        assertNull( "mineInteraction.getShortLabel2()", mineInteraction.getShortLabel2() );
        assertNull( "mineInteraction.getDetectionMethod()", mineInteraction.getDetectionMethod() );
    }

    public void testHashCode34() throws Throwable {
        MineInteractionPk pk = new MineInteractionPk();
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setPubmedId( "testMineInteractionPubmedId" );
        mineInteraction.setShortLabel2( "testMineInteractionShortLabel2" );
        mineInteraction.setWeight( 100.0 );
        mineInteraction.setShortLabel1( "testMineInteractionShortLabel1" );
        mineInteraction.setPk( pk );
        int result = mineInteraction.hashCode();
        assertEquals( "result", -565057576, result );
        assertSame( "mineInteraction.getPk()", pk, mineInteraction.getPk() );
        assertNull( "mineInteraction.getTaxid()", mineInteraction.getTaxid() );
        assertNull( "mineInteraction.getExperiment()", mineInteraction.getExperiment() );
        assertEquals( "mineInteraction.getPubmedId()", "testMineInteractionPubmedId", mineInteraction.getPubmedId() );
        assertEquals( "mineInteraction.getShortLabel1()", "testMineInteractionShortLabel1", mineInteraction.getShortLabel1() );
        assertEquals( "mineInteraction.getShortLabel2()", "testMineInteractionShortLabel2", mineInteraction.getShortLabel2() );
        assertNull( "mineInteraction.getDetectionMethod()", mineInteraction.getDetectionMethod() );
    }

    public void testHashCode35() throws Throwable {
        CvTopic detectionMethod = new CvTopic( new Institution( "testMineInteractionShortLabel" ), "testMineInteractionShortLabel" );
        MineInteractionPk pk = new MineInteractionPk();
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setPubmedId( "testMineInteractionPubmedId" );
        mineInteraction.setShortLabel2( "testMineInteractionShortLabel2" );
        mineInteraction.setDetectionMethod( detectionMethod );
        mineInteraction.setWeight( 100.0 );
        mineInteraction.setPk( pk );
        int result = mineInteraction.hashCode();
        assertEquals( "result", -182399221, result );
        assertSame( "mineInteraction.getPk()", pk, mineInteraction.getPk() );
        assertNull( "mineInteraction.getTaxid()", mineInteraction.getTaxid() );
        assertNull( "mineInteraction.getExperiment()", mineInteraction.getExperiment() );
        assertEquals( "mineInteraction.getPubmedId()", "testMineInteractionPubmedId", mineInteraction.getPubmedId() );
        assertNull( "mineInteraction.getShortLabel1()", mineInteraction.getShortLabel1() );
        assertEquals( "mineInteraction.getShortLabel2()", "testMineInteractionShortLabel2", mineInteraction.getShortLabel2() );
        assertSame( "mineInteraction.getDetectionMethod()", detectionMethod, mineInteraction.getDetectionMethod() );
    }

    public void testHashCode36() throws Throwable {
        CvTopic detectionMethod = new CvTopic( new Institution( "testMineInteractionShortLabel1" ), "testMineInteractionShortLabel" );
        Experiment experiment = new Experiment( new Institution( "testMineInteractionShortLabel2" ), "testMineInteractionShortLabel", new BioSource( new Institution( "testMineInteractionShortLabel" ), "testMineInteractionShortLabel", "-68833" ) );
        MineInteractionPk pk = new MineInteractionPk();
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setShortLabel2( "testMineInteractionShortLabel2" );
        mineInteraction.setDetectionMethod( detectionMethod );
        mineInteraction.setWeight( 100.0 );
        mineInteraction.setExperiment( experiment );
        mineInteraction.setPk( pk );
        int result = mineInteraction.hashCode();
        assertEquals( "result", -314720987, result );
        assertSame( "mineInteraction.getPk()", pk, mineInteraction.getPk() );
        assertNull( "mineInteraction.getTaxid()", mineInteraction.getTaxid() );
        assertSame( "mineInteraction.getExperiment()", experiment, mineInteraction.getExperiment() );
        assertNull( "mineInteraction.getPubmedId()", mineInteraction.getPubmedId() );
        assertNull( "mineInteraction.getShortLabel1()", mineInteraction.getShortLabel1() );
        assertEquals( "mineInteraction.getShortLabel2()", "testMineInteractionShortLabel2", mineInteraction.getShortLabel2() );
        assertSame( "mineInteraction.getDetectionMethod()", detectionMethod, mineInteraction.getDetectionMethod() );
    }

    public void testHashCode37() throws Throwable {
        MineInteractionPk pk = new MineInteractionPk();
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setPubmedId( "testMineInteractionPubmedId" );
        mineInteraction.setShortLabel2( "testMineInteractionShortLabel2" );
        mineInteraction.setWeight( 100.0 );
        mineInteraction.setTaxid( "testMineInteractionTaxid" );
        mineInteraction.setPk( pk );
        int result = mineInteraction.hashCode();
        assertEquals( "result", 1658942475, result );
        assertSame( "mineInteraction.getPk()", pk, mineInteraction.getPk() );
        assertEquals( "mineInteraction.getTaxid()", "testMineInteractionTaxid", mineInteraction.getTaxid() );
        assertNull( "mineInteraction.getExperiment()", mineInteraction.getExperiment() );
        assertEquals( "mineInteraction.getPubmedId()", "testMineInteractionPubmedId", mineInteraction.getPubmedId() );
        assertNull( "mineInteraction.getShortLabel1()", mineInteraction.getShortLabel1() );
        assertEquals( "mineInteraction.getShortLabel2()", "testMineInteractionShortLabel2", mineInteraction.getShortLabel2() );
        assertNull( "mineInteraction.getDetectionMethod()", mineInteraction.getDetectionMethod() );
    }

    public void testHashCode38() throws Throwable {
        CvTopic detectionMethod = new CvTopic( new Institution( "testMineInteractionShortLabel1" ), "testMineInteractionShortLabel" );
        Experiment experiment = new Experiment( new Institution( "testMineInteractionShortLabel2" ), "testMineInteractionShortLabel", new BioSource( new Institution( "testMineInteractionShortLabel" ), "testMineInteractionShortLabel", "-68833" ) );
        MineInteractionPk pk = new MineInteractionPk();
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setPubmedId( "testMineInteractionPubmedId" );
        mineInteraction.setShortLabel2( "testMineInteractionShortLabel2" );
        mineInteraction.setDetectionMethod( detectionMethod );
        mineInteraction.setWeight( 100.0 );
        mineInteraction.setExperiment( experiment );
        mineInteraction.setPk( pk );
        int result = mineInteraction.hashCode();
        assertEquals( "result", 2067267644, result );
        assertSame( "mineInteraction.getPk()", pk, mineInteraction.getPk() );
        assertNull( "mineInteraction.getTaxid()", mineInteraction.getTaxid() );
        assertSame( "mineInteraction.getExperiment()", experiment, mineInteraction.getExperiment() );
        assertEquals( "mineInteraction.getPubmedId()", "testMineInteractionPubmedId", mineInteraction.getPubmedId() );
        assertNull( "mineInteraction.getShortLabel1()", mineInteraction.getShortLabel1() );
        assertEquals( "mineInteraction.getShortLabel2()", "testMineInteractionShortLabel2", mineInteraction.getShortLabel2() );
        assertSame( "mineInteraction.getDetectionMethod()", detectionMethod, mineInteraction.getDetectionMethod() );
    }

    public void testHashCode39() throws Throwable {
        Experiment experiment = new Experiment( new Institution( "testMineInteractionShortLabel1" ), "testMineInteractionShortLabel", new BioSource( new Institution( "testMineInteractionShortLabel" ), "testMineInteractionShortLabel", "-68833" ) );
        MineInteractionPk pk = new MineInteractionPk();
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setPubmedId( "testMineInteractionPubmedId" );
        mineInteraction.setShortLabel2( "testMineInteractionShortLabel2" );
        mineInteraction.setWeight( 100.0 );
        mineInteraction.setExperiment( experiment );
        mineInteraction.setPk( pk );
        int result = mineInteraction.hashCode();
        assertEquals( "result", -1571982635, result );
        assertSame( "mineInteraction.getPk()", pk, mineInteraction.getPk() );
        assertNull( "mineInteraction.getTaxid()", mineInteraction.getTaxid() );
        assertSame( "mineInteraction.getExperiment()", experiment, mineInteraction.getExperiment() );
        assertEquals( "mineInteraction.getPubmedId()", "testMineInteractionPubmedId", mineInteraction.getPubmedId() );
        assertNull( "mineInteraction.getShortLabel1()", mineInteraction.getShortLabel1() );
        assertEquals( "mineInteraction.getShortLabel2()", "testMineInteractionShortLabel2", mineInteraction.getShortLabel2() );
        assertNull( "mineInteraction.getDetectionMethod()", mineInteraction.getDetectionMethod() );
    }

    public void testHashCode40() throws Throwable {
        CvTopic detectionMethod = new CvTopic( new Institution( "testMineInteractionShortLabel1" ), "testMineInteractionShortLabel" );
        Experiment experiment = new Experiment( new Institution( "testMineInteractionShortLabel2" ), "testMineInteractionShortLabel", new BioSource( new Institution( "testMineInteractionShortLabel" ), "testMineInteractionShortLabel", "-68833" ) );
        MineInteractionPk pk = new MineInteractionPk();
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setPubmedId( "testMineInteractionPubmedId" );
        mineInteraction.setDetectionMethod( detectionMethod );
        mineInteraction.setWeight( 100.0 );
        mineInteraction.setExperiment( experiment );
        mineInteraction.setPk( pk );
        int result = mineInteraction.hashCode();
        assertEquals( "result", 1490354607, result );
        assertSame( "mineInteraction.getPk()", pk, mineInteraction.getPk() );
        assertNull( "mineInteraction.getTaxid()", mineInteraction.getTaxid() );
        assertSame( "mineInteraction.getExperiment()", experiment, mineInteraction.getExperiment() );
        assertEquals( "mineInteraction.getPubmedId()", "testMineInteractionPubmedId", mineInteraction.getPubmedId() );
        assertNull( "mineInteraction.getShortLabel1()", mineInteraction.getShortLabel1() );
        assertNull( "mineInteraction.getShortLabel2()", mineInteraction.getShortLabel2() );
        assertSame( "mineInteraction.getDetectionMethod()", detectionMethod, mineInteraction.getDetectionMethod() );
    }

    public void testSetDetectionMethod() throws Throwable {
        CvTopic detectionMethod = new CvTopic( new Institution( "testMineInteractionShortLabel" ), "testMineInteractionShortLabel" );
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setDetectionMethod( detectionMethod );
        assertSame( "mineInteraction.getDetectionMethod()", detectionMethod, mineInteraction.getDetectionMethod() );
    }

    public void testSetExperiment() throws Throwable {
        MineInteraction mineInteraction = new MineInteraction();
        Experiment experiment = ( Experiment ) Mockingbird.getProxyObject( Experiment.class );
        Mockingbird.enterTestMode();
        mineInteraction.setExperiment( experiment );
        assertSame( "mineInteraction.getExperiment()", experiment, mineInteraction.getExperiment() );
    }

    public void testSetGraphId() throws Throwable {
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setGraphId( 100 );
        assertEquals( "mineInteraction.getGraphId()", 100, mineInteraction.getGraphId() );
    }

    public void testSetInteractionAc() throws Throwable {
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setInteractionAc( "testMineInteractionInteractionAc" );
        assertEquals( "mineInteraction.getInteractionAc()", "testMineInteractionInteractionAc", mineInteraction.getInteractionAc() );
    }

    public void testSetPk() throws Throwable {
        MineInteraction mineInteraction = new MineInteraction();
        MineInteractionPk pk = new MineInteractionPk();
        mineInteraction.setPk( pk );
        assertSame( "mineInteraction.getPk()", pk, mineInteraction.getPk() );
    }

    public void testSetProtein1Ac() throws Throwable {
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setProtein1Ac( "testMineInteractionProtein1Ac" );
        assertEquals( "mineInteraction.getProtein1Ac()", "testMineInteractionProtein1Ac", mineInteraction.getProtein1Ac() );
    }

    public void testSetProtein2Ac() throws Throwable {
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setProtein2Ac( "testMineInteractionProtein2Ac" );
        assertEquals( "mineInteraction.getProtein2Ac()", "testMineInteractionProtein2Ac", mineInteraction.getProtein2Ac() );
    }

    public void testSetPubmedId() throws Throwable {
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setPubmedId( "testMineInteractionPubmedId" );
        assertEquals( "mineInteraction.getPubmedId()", "testMineInteractionPubmedId", mineInteraction.getPubmedId() );
    }

    public void testSetShortLabel1() throws Throwable {
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setShortLabel1( "testMineInteractionShortLabel1" );
        assertEquals( "mineInteraction.getShortLabel1()", "testMineInteractionShortLabel1", mineInteraction.getShortLabel1() );
    }

    public void testSetShortLabel2() throws Throwable {
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setShortLabel2( "testMineInteractionShortLabel2" );
        assertEquals( "mineInteraction.getShortLabel2()", "testMineInteractionShortLabel2", mineInteraction.getShortLabel2() );
    }

    public void testSetTaxid() throws Throwable {
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setTaxid( "testMineInteractionTaxid" );
        assertEquals( "mineInteraction.getTaxid()", "testMineInteractionTaxid", mineInteraction.getTaxid() );
    }

    public void testSetWeight() throws Throwable {
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setWeight( 100.0 );
        assertEquals( "mineInteraction.getWeight()", 100.0, mineInteraction.getWeight(), 1.0E-6 );
    }

//    public void testConstructorThrowsNullPointerException() throws Throwable {
//        ProteinImpl protein1 = ( ProteinImpl ) Mockingbird.getProxyObject( ProteinImpl.class );
//        InteractionImpl interaction = ( InteractionImpl ) Mockingbird.getProxyObject( InteractionImpl.class );
//        Mockingbird.enterRecordingMode();
//        Mockingbird.setReturnValue( protein1.getShortLabel(), "testString" );
//        Mockingbird.enterTestMode();
//        try {
//            new MineInteraction( protein1, null, interaction );
//            fail( "Expected NullPointerException to be thrown" );
//        } catch ( NullPointerException ex ) {
//            assertNull( "ex.getMessage()", ex.getMessage() );
//            assertThrownBy( MineInteraction.class, ex );
//            assertInvoked( protein1, "getShortLabel" );
//        }
//    }

    public void testConstructorThrowsNullPointerException1() throws Throwable {
        try {
            new MineInteraction( null, new ProteinImpl( new Institution( "testMineInteractionShortLabel1" ), new BioSource( new Institution( "testMineInteractionShortLabel" ), "testMineInteractionShortLabel", "-68833" ), "testMineInteractionShortLabel" ), new InteractionImpl( new ArrayList( 100 ), null, "testMineInteractionShortLabel", new Institution( "testMineInteractionShortLabel2" ) ) );
            fail( "Expected NullPointerException to be thrown" );
        } catch ( NullPointerException ex ) {
            assertNull( "ex.getMessage()", ex.getMessage() );
            assertThrownBy( MineInteraction.class, ex );
        }
    }

    public void testHashCodeThrowsNullPointerException() throws Throwable {
        Experiment experiment = new Experiment( new Institution( "testMineInteractionShortLabel" ), "testMineInteractionShortLabel", null );
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setShortLabel2( "testMineInteractionShortLabel2" );
        mineInteraction.setExperiment( experiment );
        mineInteraction.setShortLabel1( "testMineInteractionShortLabel1" );
        try {
            mineInteraction.hashCode();
            fail( "Expected NullPointerException to be thrown" );
        } catch ( NullPointerException ex ) {
            assertNull( "ex.getMessage()", ex.getMessage() );
            assertThrownBy( Experiment.class, ex );
            assertNull( "mineInteraction.getPk()", mineInteraction.getPk() );
            assertNull( "mineInteraction.getTaxid()", mineInteraction.getTaxid() );
            assertNull( "mineInteraction.getPubmedId()", mineInteraction.getPubmedId() );
            assertEquals( "mineInteraction.getShortLabel1()", "testMineInteractionShortLabel1", mineInteraction.getShortLabel1() );
            assertEquals( "mineInteraction.getShortLabel2()", "testMineInteractionShortLabel2", mineInteraction.getShortLabel2() );
            assertSame( "mineInteraction.getExperiment()", experiment, mineInteraction.getExperiment() );
            assertNull( "mineInteraction.getDetectionMethod()", mineInteraction.getDetectionMethod() );
        }
    }

    public void testHashCodeThrowsNullPointerException1() throws Throwable {
        Experiment experiment = new Experiment( new Institution( "testMineInteractionShortLabel" ), "testMineInteractionShortLabel", null );
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setExperiment( experiment );
        mineInteraction.setShortLabel1( "testMineInteractionShortLabel1" );
        mineInteraction.setTaxid( "testMineInteractionTaxid" );
        try {
            mineInteraction.hashCode();
            fail( "Expected NullPointerException to be thrown" );
        } catch ( NullPointerException ex ) {
            assertNull( "ex.getMessage()", ex.getMessage() );
            assertThrownBy( Experiment.class, ex );
            assertNull( "mineInteraction.getPk()", mineInteraction.getPk() );
            assertEquals( "mineInteraction.getTaxid()", "testMineInteractionTaxid", mineInteraction.getTaxid() );
            assertNull( "mineInteraction.getPubmedId()", mineInteraction.getPubmedId() );
            assertEquals( "mineInteraction.getShortLabel1()", "testMineInteractionShortLabel1", mineInteraction.getShortLabel1() );
            assertNull( "mineInteraction.getShortLabel2()", mineInteraction.getShortLabel2() );
            assertSame( "mineInteraction.getExperiment()", experiment, mineInteraction.getExperiment() );
            assertNull( "mineInteraction.getDetectionMethod()", mineInteraction.getDetectionMethod() );
        }
    }

    public void testHashCodeThrowsNullPointerException2() throws Throwable {
        MineInteractionPk pk = new MineInteractionPk();
        Experiment experiment = Experiment.getShallowCopy( Experiment.getShallowCopy( new Experiment( new Institution( "testMineInteractionShortLabel" ), "testMineInteractionShortLabel", null ) ) );
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setShortLabel2( "testMineInteractionShortLabel2" );
        mineInteraction.setExperiment( experiment );
        mineInteraction.setTaxid( "testMineInteractionTaxid" );
        mineInteraction.setPk( pk );
        try {
            mineInteraction.hashCode();
            fail( "Expected NullPointerException to be thrown" );
        } catch ( NullPointerException ex ) {
            assertNull( "ex.getMessage()", ex.getMessage() );
            assertThrownBy( Experiment.class, ex );
            assertSame( "mineInteraction.getPk()", pk, mineInteraction.getPk() );
            assertEquals( "mineInteraction.getTaxid()", "testMineInteractionTaxid", mineInteraction.getTaxid() );
            assertNull( "mineInteraction.getPubmedId()", mineInteraction.getPubmedId() );
            assertNull( "mineInteraction.getShortLabel1()", mineInteraction.getShortLabel1() );
            assertEquals( "mineInteraction.getShortLabel2()", "testMineInteractionShortLabel2", mineInteraction.getShortLabel2() );
            assertSame( "mineInteraction.getExperiment()", experiment, mineInteraction.getExperiment() );
            assertNull( "mineInteraction.getDetectionMethod()", mineInteraction.getDetectionMethod() );
        }
    }

    public void testHashCodeThrowsNullPointerException3() throws Throwable {
        MineInteractionPk pk = new MineInteractionPk();
        Experiment experiment = Experiment.getShallowCopy( Experiment.getShallowCopy( new Experiment( new Institution( "testMineInteractionShortLabel" ), "testMineInteractionShortLabel", null ) ) );
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setExperiment( experiment );
        mineInteraction.setShortLabel1( "testMineInteractionShortLabel1" );
        mineInteraction.setTaxid( "testMineInteractionTaxid" );
        mineInteraction.setPk( pk );
        try {
            mineInteraction.hashCode();
            fail( "Expected NullPointerException to be thrown" );
        } catch ( NullPointerException ex ) {
            assertNull( "ex.getMessage()", ex.getMessage() );
            assertThrownBy( Experiment.class, ex );
            assertSame( "mineInteraction.getPk()", pk, mineInteraction.getPk() );
            assertEquals( "mineInteraction.getTaxid()", "testMineInteractionTaxid", mineInteraction.getTaxid() );
            assertNull( "mineInteraction.getPubmedId()", mineInteraction.getPubmedId() );
            assertEquals( "mineInteraction.getShortLabel1()", "testMineInteractionShortLabel1", mineInteraction.getShortLabel1() );
            assertNull( "mineInteraction.getShortLabel2()", mineInteraction.getShortLabel2() );
            assertSame( "mineInteraction.getExperiment()", experiment, mineInteraction.getExperiment() );
            assertNull( "mineInteraction.getDetectionMethod()", mineInteraction.getDetectionMethod() );
        }
    }

    public void testHashCodeThrowsNullPointerException4() throws Throwable {
        Experiment experiment = new Experiment( new Institution( "testMineInteractionShortLabel" ), "testMineInteractionShortLabel", null );
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setShortLabel2( "testMineInteractionShortLabel2" );
        mineInteraction.setExperiment( experiment );
        mineInteraction.setShortLabel1( "testMineInteractionShortLabel1" );
        mineInteraction.setTaxid( "testMineInteractionTaxid" );
        try {
            mineInteraction.hashCode();
            fail( "Expected NullPointerException to be thrown" );
        } catch ( NullPointerException ex ) {
            assertNull( "ex.getMessage()", ex.getMessage() );
            assertThrownBy( Experiment.class, ex );
            assertNull( "mineInteraction.getPk()", mineInteraction.getPk() );
            assertEquals( "mineInteraction.getTaxid()", "testMineInteractionTaxid", mineInteraction.getTaxid() );
            assertNull( "mineInteraction.getPubmedId()", mineInteraction.getPubmedId() );
            assertEquals( "mineInteraction.getShortLabel1()", "testMineInteractionShortLabel1", mineInteraction.getShortLabel1() );
            assertEquals( "mineInteraction.getShortLabel2()", "testMineInteractionShortLabel2", mineInteraction.getShortLabel2() );
            assertSame( "mineInteraction.getExperiment()", experiment, mineInteraction.getExperiment() );
            assertNull( "mineInteraction.getDetectionMethod()", mineInteraction.getDetectionMethod() );
        }
    }

    public void testHashCodeThrowsNullPointerException5() throws Throwable {
        Experiment experiment = new Experiment( new Institution( "testMineInteractionShortLabel" ), "testMineInteractionShortLabel", null );
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setShortLabel2( "testMineInteractionShortLabel2" );
        mineInteraction.setExperiment( experiment );
        mineInteraction.setTaxid( "testMineInteractionTaxid" );
        try {
            mineInteraction.hashCode();
            fail( "Expected NullPointerException to be thrown" );
        } catch ( NullPointerException ex ) {
            assertNull( "ex.getMessage()", ex.getMessage() );
            assertThrownBy( Experiment.class, ex );
            assertNull( "mineInteraction.getPk()", mineInteraction.getPk() );
            assertEquals( "mineInteraction.getTaxid()", "testMineInteractionTaxid", mineInteraction.getTaxid() );
            assertNull( "mineInteraction.getPubmedId()", mineInteraction.getPubmedId() );
            assertNull( "mineInteraction.getShortLabel1()", mineInteraction.getShortLabel1() );
            assertEquals( "mineInteraction.getShortLabel2()", "testMineInteractionShortLabel2", mineInteraction.getShortLabel2() );
            assertSame( "mineInteraction.getExperiment()", experiment, mineInteraction.getExperiment() );
            assertNull( "mineInteraction.getDetectionMethod()", mineInteraction.getDetectionMethod() );
        }
    }

    public void testHashCodeThrowsNullPointerException6() throws Throwable {
        MineInteractionPk pk = new MineInteractionPk();
        Experiment experiment = Experiment.getShallowCopy( Experiment.getShallowCopy( new Experiment( new Institution( "testMineInteractionShortLabel" ), "testMineInteractionShortLabel", null ) ) );
        MineInteraction mineInteraction = new MineInteraction();
        mineInteraction.setShortLabel2( "testMineInteractionShortLabel2" );
        mineInteraction.setExperiment( experiment );
        mineInteraction.setShortLabel1( "testMineInteractionShortLabel1" );
        mineInteraction.setTaxid( "testMineInteractionTaxid" );
        mineInteraction.setPk( pk );
        try {
            mineInteraction.hashCode();
            fail( "Expected NullPointerException to be thrown" );
        } catch ( NullPointerException ex ) {
            assertNull( "ex.getMessage()", ex.getMessage() );
            assertThrownBy( Experiment.class, ex );
            assertSame( "mineInteraction.getPk()", pk, mineInteraction.getPk() );
            assertEquals( "mineInteraction.getTaxid()", "testMineInteractionTaxid", mineInteraction.getTaxid() );
            assertNull( "mineInteraction.getPubmedId()", mineInteraction.getPubmedId() );
            assertEquals( "mineInteraction.getShortLabel1()", "testMineInteractionShortLabel1", mineInteraction.getShortLabel1() );
            assertEquals( "mineInteraction.getShortLabel2()", "testMineInteractionShortLabel2", mineInteraction.getShortLabel2() );
            assertSame( "mineInteraction.getExperiment()", experiment, mineInteraction.getExperiment() );
            assertNull( "mineInteraction.getDetectionMethod()", mineInteraction.getDetectionMethod() );
        }
    }
}

